select * from customer limit 20;
--1.what is the total revenue generated by male vs female customers ?
select gender, sum(purchase_amount) as revenue from customer  group by gender;

--2.which customers used a discount but still spent more than the average purchase amount?
select customer_id , purchase_amount from customer where discount_applied='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

--3.which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::NUMERIC),2) as "Average prodcut rating" --here we changed the datatype of purchase amount to numeric
from customer
group by  item_purchased
order by avg(review_rating) desc
limit 5;

-- 4.compare the average Purchase Amounts between Standard and express shipping.
select shipping_type, Round(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- 5.Do subscribed customers spend more? Compare average spend and total revenue b/w subscribers and non-subscribers?
select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount),2) as average_spend, sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by average_spend , total_revenue desc;

-- 6.which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied= 'Yes' Then 1 Else 0 END)/Count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
--by this question 6 we come to know which product is heavly depends on the discount

-- 7.segment customers into new, Returning and loyal based on their total number of previous purchases and show the count of each segment. 
with customer_type as(
select customer_id , previous_purchases,
case
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer
)
select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;